title: wither.blog
description: "Binary Exploitation, C Development, CTFs, and More."
baseurl: ""
url: "https://wither.blog/"
github_username: wither

permalink: /:slug.html

favicon: "favicon.png"
goat_counter: "wither" # put your GoatCounter name if you want to use GoatCounter analytics

# Build settings
remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light"
  back_home_text: "../" # customize text for homepage link in post layout
  date_format: "%Y-%m" # customize how date is formatted in post list
  show_description: true # show blog description in home page
  lowercase_titles: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
